### ISSUE TITLE
When unknown product and extra received items synchro fails

### ISSUE THREAD

**Issue by souly84** [souly84/Warehouse.Mobile#8]
Step to reproduce:
Reception
Select a supplier
Scan item in the list => item disappear and marked as confirmed
Scan the same item one more time => Yellow line appear at top stating the item is extra received
Scan an item which is not in the list => Red lie appear at top stating the item is not expected
Press validate button => Error message "KeyNotFoundException: The given key 'EAN' was not present in the dictionary."

**Comment by DenisZhukovsky** [comment]
could you please add Json data for reception goods
